### ISSUE TITLE
Request Validation validates child properties even when optional parent is missing

### ISSUE THREAD

**Issue by ryshep111** [BlueOakJS/blueoak-server#107]
```
- name: body
          in: body
          description: optional user and transaction objects to persist to session
          required: false
          schema:
            type: object
            required:
              - user
            properties:
              user:
                $ref: ./definitions/userObj.yaml
              transaction:
                $ref: ./definitions/transactionObj.yaml
```
With this yaml, BOS still validates that user exists even when the optional request body is not supplied.

Using version 2.10.2
