### ISSUE TITLE
format validation message does not indicate the field that faild

### ISSUE THREAD

**Issue by seanpk** [BlueOakJS/blueoak-server#57]
I've got a zip code query parameter called `zip`, but when a bad zip code is sent, it the message doesn't indicate it in the "field" parameter.

Here's the message:
```json
{
  "message": "Error validating query parameter zip",
  "type": "ValidationError",
  "status": 422,
  "validation_errors": [
    {
      "message": "String does not match pattern: ^(\\d{5})(?:-(\\d{4}))?$",
      "field": ""
    }
  ]
}
```

Here's the query parameter swagger:
```yaml
name: zip
in: query
required: false
type: string
pattern: ^(\d{5})(?:-(\d{4}))?$
description: |
  A string representing the USPS zip code for which records should be returned.
```

I expect the respond to be as-is with this update: `"field": "zip"`.
